-- Drop tables if they exist to allow clean re-runs
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Transactions CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ParkingSpots CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Create ParkingSpots Table
CREATE TABLE ParkingSpots (
    SpotID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SpotType VARCHAR2(50) NOT NULL,
    IsOccupied CHAR(1) DEFAULT 'N' CHECK (IsOccupied IN ('Y', 'N'))
);

-- Create Transactions Table
CREATE TABLE Transactions (
    TransactionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LicensePlate VARCHAR2(20) NOT NULL,
    SpotID NUMBER REFERENCES ParkingSpots(SpotID),
    EntryTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ExitTime TIMESTAMP,
    TotalFee NUMBER(10, 2)
);

-- Insert seed data for ParkingSpots (5 spots total)
INSERT INTO ParkingSpots (SpotType, IsOccupied) VALUES ('Regular', 'N');
INSERT INTO ParkingSpots (SpotType, IsOccupied) VALUES ('Regular', 'N');
INSERT INTO ParkingSpots (SpotType, IsOccupied) VALUES ('Compact', 'N');
INSERT INTO ParkingSpots (SpotType, IsOccupied) VALUES ('Handicap', 'N');
INSERT INTO ParkingSpots (SpotType, IsOccupied) VALUES ('Regular', 'N');
COMMIT;
